apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: web-svc
spec:
  selector:
    app: myweb
  type: NodePort
  ports:
    - nodePort: 31180
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
    template:
      metadata:
        name: webpod
        labels:   
          app: webapp
        spec:
          containers:
            - name: httpcont
              image: httpd
              ports:
                -  containerPort: 80